version: '3.8'

services:
  mindfulmate:
    build: 
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DEBUG=false
      - LOG_LEVEL=INFO
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - mindfulmate-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
    networks:
      - mindfulmate-network
    # Uncomment if you have GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama-data:

networks:
  mindfulmate-network:
    driver: bridge